set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO0]
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO1]
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO2]
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO3]
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_SS0]
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_CLK]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_CMD] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CMD]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D0]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D1]
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CLK]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D2]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D3]